### ISSUE TITLE
create basic opendcre module

### ISSUE THREAD

**Issue by acencini** [vapor-ware/synse-cli#1]
We can start VESH by mapping opendcre into the CLI as a module.  TODO is designing the syntax of the commands, but the prototype mapping that already exists in vesh-cli seems to make sense.  We will need to add auth and TLS to this as well.  From there, we can move up the stack and add routing-specific stuff that allows VESH to hit the routing API and map commands to chambers, racks, etc.

**Comment by edaniszewski** [comment]
@timfallmk I think this is also now out of the scope of Synse and I would also be good with closing this one.
