### ISSUE TITLE
improve timestamp output formatting

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-cli#103]
in the v2 work, the timestamp output looks something like 
```
TYPE          VALUE     TIMESTAMP
temperature   43        2018-02-14 13:55:12.243940663 &#43;0000 UTC m=&#43;46240.844484311
```

which is a lot..

ideally, I think it should look something more like
```
TYPE          VALUE     TIMESTAMP
temperature   43        2018-02-14 13:55:12.243940663
```

**Comment by timfallmk** [comment]
Some (debatably) good reference for this in https://github.com/vapor-ware/ksync/blob/master/cmd/ksync/version.go#L53
