### ISSUE TITLE
Version printing for local and no host

### ISSUE THREAD

**Issue by timfallmk** [vapor-ware/synse-cli#112]
Related to #50 

We should probably modify the version command to print the _local_ version as well (similar to kysnc's stamps during build). This would also have something to print out (instead of an error) in the case that no host is properly configured.

**Comment by edaniszewski** [comment]
This sounds good to me. I think currently cli version is printed w/ the `--version` flag, but that seems fine to keep around.

**Comment by timfallmk** [comment]
@edaniszewski If by currently, you mean in `1.0`, then yes I think so. For `ksync` , `ksync version` prints out the local, followed by the remote *if it detects (silently) that the remote is available*

**Comment by edaniszewski** [comment]
Not sure we want `version` to print both local and server version anymore since we have updated the command structure. E.g.
```
synse server version
```
seems like it should only give the version of only the server. Just some thoughts

**Comment by timfallmk** [comment]
I think that's fine, it makes more sense given the way we have it now.
