### ISSUE TITLE
Move `--format` to global flag

### ISSUE THREAD

**Issue by timfallmk** [vapor-ware/synse-cli#113]
Should we move the `--format` flag to the global flag list? I know it doesn't apply to some commands, but those are probably the exception rather than the majority. That way it can also be set in the config, along with log level and such.

**Comment by edaniszewski** [comment]
I'm not sure. I guess it depends on a couple things. To start, I don't *think* we have a `--format` flag, but I think you are referring to the `--output` flag that a bunch of commands have to specify JSON or YAML output. 

This is different from what I would consider "format", where my idea of a `--format` flag would follow the docker cli approach (e.g. https://docs.docker.com/engine/reference/commandline/images/#format-the-output)

I think for `--output` it would probably be fine to have it as a global flag, my only trepidation there is that it could make the command usage look a bit weird 
```
synse --output json info rack-1
```
as opposed to
```
synse info rack-1 --output json
```

or do you mean just having it be
```
synse --output json
```
which would then set all subsequent responses to JSON output? In which case, would we still allow something like
```shell
# set default output to json
synse --output json

# override the default for this command
synse info rack-1 --output yaml
```

**Comment by edaniszewski** [comment]
for a `--format` flag similar to docker, I think that has to be per command since the formatting possibilities are dependent on the command.

**Comment by timfallmk** [comment]
I see your distinction here. I would actually reverse the two definitions, but that's just pedantic.

**Comment by edaniszewski** [comment]
So what you're suggesting would be to have something like
```
synse --format yaml host list
```
and not to do any of the output modification via Go Template strings?

If so, that doesn't sound too bad to me, but I still sorta feel like its an awkward place for the flag, based off of other CLIs I've used (e.g. kubectl, docker), though I've admittedly not looked at a lot of other tools so maybe I'm just picking the two examples that do it with formatting as a command flag and everything else has formatting as a global flag.

**Comment by timfallmk** [comment]
I think including the go-template based "filter" (that's probably what I would call it but it's just a suggestion), is perfectly fine. It might have been more of an assignment of functions thing.

If your worry is around sequencing, the cli is _somewhat _ flexible when it comes to ordering. As long as global flags don't overlap with command specific flags or arguments, it usually works™. I could also be misunderstanding your concern.

Here would be an example of usage I was thinking of:

Person manually using the CLI from a TTY:

```shell
synse --format pretty host list
```
(presumably that would be the default and could be omitted)

Person using the CLI in a script to do automation:

```shell
synse --format json host list
```

That's where I was thinking, but maybe I'm wrong.

**Comment by edaniszewski** [comment]
This all sounds good to me. 👍 

A separate issue from this one (but since we're here..): `--filter` already exists (on `scan` only) to filter based on a value, e.g. unfiltered
```
➜ synse scan
RACK      BOARD     DEVICE                             INFO                         TYPE
rack-1    vec       329a91c6781ce92370a3c38ba9bf35b2   Synse Temperature Sensor 4   temperature
rack-1    vec       83cc1efe7e596e4ab6769e0c6e3edf88   Synse Temperature Sensor 2   temperature
rack-1    vec       d29e0bd113a484dc48fd55bd3abad6bb   Synse backup LED             led
rack-1    vec       db1e5deb43d9d0af6d80885e74362913   Synse Temperature Sensor 3   temperature
rack-1    vec       eb100067acb0c054cf877759db376b03   Synse Temperature Sensor 1   temperature
rack-1    vec       eb9a56f95b5bd6d9b51996ccd0f2329c   Synse Fan                    fan
rack-1    vec       f52d29fecf05a195af13f14c7306cfed   Synse LED                    led
rack-1    vec       f97f284037b04badb6bb7aacd9654a4e   Synse Temperature Sensor 5   temperature
```
vs. filtered
```
➜ synse scan --filter type=led
RACK      BOARD     DEVICE                             INFO               TYPE
rack-1    vec       d29e0bd113a484dc48fd55bd3abad6bb   Synse backup LED   led
rack-1    vec       f52d29fecf05a195af13f14c7306cfed   Synse LED          led
```

Im not at all married to this way of doing things, but does seem like filtering based on value could be useful, especially if there are a lot of devices present.
