### ISSUE TITLE
Command grouping and verb overlap

### ISSUE THREAD

**Issue by timfallmk** [vapor-ware/synse-cli#127]
`urfave/cli` contains the notion of "command groups" mostly to help divide logical groups of commands, which may be at the same level, in help text for users. We currently use this for `Synse Server Actions` in this way:

```shell
./synse --help
NAME:
   synse - Command line tool for interacting with Synse components

USAGE:
   synse [global options] command [command options] [arguments...]

VERSION:
   0.1.0

COMMANDS:
     hosts       Manage Synse Server instances
     plugin      Interact with Synse Plugins
     completion  Generate shell completion scripts for bash or zsh
     help, h     Shows a list of commands or help for one command

   Synse Server Actions:
     status       Get the status of the active host
     version      Get the version of the active host
     scan         Enumerate all devices on the active host
     config       Get the configuration for the active host
     plugins      Get a list of plugins that are configured with the active host
     read         Read from the specified device
     write        Write to the specified device
     info         Get info for the specified rack, board, or device
     transaction  Check the state and status of a transaction
```

I see the logical need for this where many, possibly overlapping, command groups exist but I'm not sure it makes sense here, given only one group. Is this for future inclusion of plugin (and thus to be grouped under other sections) related commands?

In addition, it means there's some odd verb overlapping. For example `synse plugin` and `synse plugins` do two logically different things. Should we nest these? Should we reorganize the whole hierarchy?

We should probably do anything we need to do before we get too far down the road of adding commands. 😄

**Comment by timfallmk** [comment]
I think it might make things more logical (for development too) if we re-nest things.

```
synse host <thing>

synse server plugins <thing>

synse plugin read <thing>
```
etc.

Thoughts?

**Comment by edaniszewski** [comment]
I was actually thinking this same thing earlier in the week. +1 from me for re-nesting things.
