### ISSUE TITLE
Bash completion for "verb" options

### ISSUE THREAD

**Issue by timfallmk** [vapor-ware/synse-cli#133]
It would benefit usability significantly to have autocomplete work for "verbs". It will need to poll data for this, but it should be doable.

**Comment by edaniszewski** [comment]
I think this would mostly be for writes, right? e.g. an LED device could autocomplete actions (color,state,blink), etc.

Are there other commands that would benefit from this? perhaps transaction, but that would require https://github.com/vapor-ware/synse-server/issues/42

**Comment by timfallmk** [comment]
Really anything that would require “filling in” of arguments. Reads, info, etc. You know the structure better than I do though.
