### ISSUE TITLE
tests failures in CI are not causing CI itself to fail

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-cli#146]
e.g. see: https://circleci.com/gh/vapor-ware/synse-cli/351

**Comment by timfallmk** [comment]
@edaniszewski This is most likely do to `make` not correctly piping the failures through. We had this before and I forgot what we did. Maybe @grampelberg remembers.

**Comment by edaniszewski** [comment]
this is "fixed" by the fact that it doesn't run `make ci-test` for the test stage, now it runs `bin/coverage.sh` (tests w/ coverage reporting).

Not sure if that's fine, or if we should fix the `ci-test` target and call `bin/coverage.sh` from there. Otherwise, we could probably get rid of said target since its not being used elsewhere..

**Comment by timfallmk** [comment]
Well I'm not Thomas, so not using `make` is fine by me :). I would check with him though to see what `make` incantation is needed for piping.

**Comment by edaniszewski** [comment]
meh, i'm just gonna call this fixed since it doesn't use make anymore. easy enough!
