### ISSUE TITLE
refactor "synse server plugins" command to be a command group

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-cli#175]
related to #174 

since we expose more info for plugins now, it would make sense to expand the "plugin" command a bit. I'm thinking something like:

```bash
$ synse server --help

Interact with Synse Server

Description:
  This sub-command allows you to interact with a Synse Server
  instance. The instance that is being interfaced with is set
  and managed by the 'synse hosts' commands.

Usage:
  synse server command [command options] [arguments...]

Commands:
  config       Get the Synse Server configuration
  info         Get info for the specified rack, board, or device
  plugin       Get information on plugins and plugin state
  read         Read from the specified device
  scan         Enumerate all devices on the active host
  status       Get the status of Synse Server
  transaction  Check the state and status of a transaction
  version      Get the version of Synse Server
  write        Write to the specified device

Options:
  --help, -h  show help
```

```
➜ synse server plugin --help

Get information on plugins and plugin state

Description:
  This sub-command allows you to get plugin metadata, such as the
  name, version, tag, etc. It also lets you get a view into the plugin health
  if any health checks are configured for the plugin.

  If no arguments are given, this will just list all configured plugins.

Usage:
  synse server plugin [command [command options] [arguments...]]

Commands:
  info         Get a complete view of a plugin's metadata
  health       Get the health status of the plugin

Options:
  --help, -h  show help
```

These are just my initial thoughts, so they can be changed around for whatever makes the most sense.

**Comment by hoanhan101** [comment]
If `synse server plugin` gets information of a list of plugins without args, would it make more sense to name it `synse server plugins` instead?

Also, for these sub command below, do we want to get a list of info and health of all configured plugins or we want to specify what plugin to display these information.
```
Commands:
  info         Get a complete view of a plugin's metadata
  health       Get the health status of the plugin
```

**Comment by edaniszewski** [comment]
i think you're right. calling it `synse server plugins` seems like it makes more sense.

**Comment by hoanhan101** [comment]
If we call it `synse server plugins`, then does `synse server plugins info` mean listing all the plugins' metadata informations? I edited the comment above to ask this but maybe you answered before it was changed.

**Comment by edaniszewski** [comment]
I think that `synse server plugins info` would list all the plugins' metadata. We could also allow for an optional arg, the plugin name, to filter by that, e.g. `synse server plugins info vaporio/emulator-plugin` would get the info only for the emulator plugin
