### ISSUE TITLE
add flag for `plugin` subcommand to pass in cert

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-cli#198]
as of SDK 1.1.0, the grpc layer can use TLS, so we will need to be able to pass in a cert to a TLS-enabled plugin in order to get a response back.

**Comment by timfallmk** [comment]
Nooooooooo!

**Comment by timfallmk** [comment]
Just kidding. Everything is fine.

**Comment by edaniszewski** [comment]
look at you, mr. doing-things-the-right-way
