### ISSUE TITLE
add mass cli audit via vesh

### ISSUE THREAD

**Issue by acencini** [vapor-ware/synse-cli#4]
from @vaporcole --

something like:

`vesh opendcre scan --led` - return all led statuses from a rack, same goes for temp, power, etc.

**Comment by edaniszewski** [comment]
perhaps this could be done via a `--filter` flag. either way, I think this is further out. need to get it working with synse 2.0 first.

**Comment by edaniszewski** [comment]
I believe this is fixed w/ scan filtering?
```
➜ synse scan --filter type=led
RACK      BOARD     DEVICE                             INFO               TYPE
rack-1    vec       d29e0bd113a484dc48fd55bd3abad6bb   Synse backup LED   led
rack-1    vec       f52d29fecf05a195af13f14c7306cfed   Synse LED          led
```

I guess that all depends on what "statuses" means in the original issue comment. If it means the device state in Synse Server, then this is complete. If it means reading all devices of a different type, then this is an issue that needs more thought and is definitely further down the road than 2.0

@timfallmk  thoughts?

**Comment by timfallmk** [comment]
@edaniszewski Originally, I think it meant both. This was easier in 1.0 where `scan` simply returned everything. It's useful to have something like that, but as long as `scan` and `scan --filter` exist (assuming they work the way I'm imagining) I think that should cover it.

**Comment by edaniszewski** [comment]
@timfallmk  I think this is good to close
