### ISSUE TITLE
add support for synse v2.0

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-cli#50]
we will need to do some updates here to get this working with the v2.0 API. 

In addition to that, we will need to set up version checking against Synse Server to know what API schema to use. (Synse Server version can be retrieved via `GET .../synse/version`

**Comment by timfallmk** [comment]
@edaniszewski Agreed. I think maintaining function between the two major branches for a little while is ok. Do we have a schema for 2.0 yet?

Should I assign this to you for the time being?

**Comment by edaniszewski** [comment]
we mostly have a 2.0 schema. still have some work to do there to get it all right, but should take too long. this can be assigned to me. it'll be a little while until I get to it, but overall it doesn't look like it'll be too bad.

**Comment by edaniszewski** [comment]
For the most part, I think the core synse 2.0 routes are implemented and working here. don't have the alias routes in yet, but that shouldn't be too hard. That said, there is still a bunch of work to be done. For example, filtering scan results, better output formatting, more debug logging, more uniform error messaging, bash completion, better documentation, ......

There's also the work for adding plugin support, but I think that is separate from this.

I'll probably spend some time going through and putting together a list of remaining work items here and eventually translate that into github issues.

**Comment by timfallmk** [comment]
Looks good. I'll try and test it when I get the chance.

FYI, test coverage and documentation would be great. Bash completion exists already (and should work for any new commands added).
![](https://i.imgur.com/aLbIZoE.gif)

**Comment by edaniszewski** [comment]
v2 support is pretty much all in the v2.0 branch. I believe most of the other work here is more cli related than 2.0 related, so I move to close this as done

**Comment by timfallmk** [comment]
@edaniszewski I'm good with a merge of `2.0` into master and cutting a new release. I think it's mostly good to go.
