### ISSUE TITLE
add functionality for plugin management

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-cli#51]
there is a super lightweight CLI for doing basic things with v2.0 plugins. this is mostly around debug/development (e.g. direct read/write/etc). something I've been thinking about is whether it should remain a separate thing or whether it could be moved here, making this the CLI for everything synse-related. 

opening this mostly just to get thoughts and foster discussion. more work items could fall out of the results of this.

**Comment by timfallmk** [comment]
@edaniszewski Since the goal was pretty simple, I think it would be awesome to move it here. That would certainly make this more useful for daily use.

**Comment by edaniszewski** [comment]
👍  👍  👍
