### ISSUE TITLE
remove vestiges of 'vesh'

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-cli#52]
the CLI is now called 'synse', not 'vesh', so we should remove remaining references to vesh.

**Comment by timfallmk** [comment]
@edaniszewski Aside from the top level "main" file (and it's test) I don't see anything else. Did you catch other references?

FYI There's probably still some git references since the repo changed names, but I'm not sure those matter much.

**Comment by edaniszewski** [comment]
I thought I saw it somewhere else, but it could have just been in an old doc. After doing a search, looks like the CircleCI badge in the README is pointing to the vesh repo.

**Comment by timfallmk** [comment]
Yeah, those two look like the only remaining ones. I'll try to remember to roll this into the next PR.
