### ISSUE TITLE
URL to page that does not exist

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-cli#53]
in `vesh.go`:

> // Synse provides a cli to vapor.io infrastructure. Specifically it allows access
// to the Synse (http://www.vapor.io/synse/) REST API for running commands
// against connected infrastructure and devices.

The URL points to a page that doesn't exist.

**Comment by timfallmk** [comment]
Balls.

**Comment by edaniszewski** [comment]
Yeah. I'm really fun at parties.

**Comment by edaniszewski** [comment]
this is fixed in the 2.0 work
