### ISSUE TITLE
Add Makefile with targets for common development tasks

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-cli#55]
e.g. building, testing, formatting, linting, etc. Not totally necessary, but makes development a little easier.

I have a Makefile that has these things in other repos that can be added here.

**Comment by timfallmk** [comment]
@edaniszewski Someone's been attending the school of @pyronicide

**Comment by edaniszewski** [comment]
<img src="https://cdn-images-1.medium.com/max/1600/1*6k_7CixkGjI-PS2UYAmLZw.jpeg" />
